### ISSUE TITLE
callback_secret

### ISSUE THREAD

**Issue by gcphost** [hostvpn/whmcs-coinbase-bitcoin#4]
Hi

It says to set the 'callback_secret' in coinbase but I do not see this on their site.

Can you point us in the right direction?

I also tested their callback ipn and it does not show 'secret' as being sent back to the script.

**Comment by hostvpn** [comment]
This is for the callback URL in the Merchant Settings area of Coinbase.  Essentially your callback URL should look like:

https://yourdomain.com/whmcs/modules/gateways/callback/coinbase.php?secret=SOMERANDOMSTRINGTHATISVERY@Long

You would take the paramter for 'secret' and use that for the setting in WHMCS for "Coinbase Callback Secret".

Hope that helps!
