### ISSUE TITLE
Payment goes through but invoice isn't updated

### ISSUE THREAD

**Issue by allinfinite** [hostvpn/whmcs-coinbase-bitcoin#5]
The payment goes through fine but the invoice isn't updated to "Paid" the user is left on the payment gateway screen.. the plugin displays "Paid" but just stays on that screen
![screen shot 2014-01-13 at 10 59 04 am](https://f.cloud.github.com/assets/2475429/1905037/bc70216c-7c98-11e3-8c20-0a63872a81ba.png)

**Comment by hostvpn** [comment]
Thanks for letting me know.  I'm not able to fully test this yet, but I think this will work.  Can you edit the callback/coinbase.php and comment out line 56 (the addInvoicePayment function)?

Then add the following code:

```
    $command = "addinvoicepayment";
    $values["invoiceid"] = $invoice_id;
    $values["transid"] = $trans_id;
    $values["amount"] = $amount;
    $values["fee"] = $fee;
    $values["gateway"] = $GATEWAY['name'];
    $results = localAPI($command,$values,$adminuser);
```

Please let me know if that works and I'll update the repo.  I believe one of the newer WHMCS versions broke or disabled that function (addInvoicePayment).  Thanks!

**Comment by hostvpn** [comment]
I pushed out the new change to the repo which I believe is working, so I'll mark this as closed for now.

**Comment by allinfinite** [comment]
No luck.. any thing else to try?

**Comment by hostvpn** [comment]
Feel free to email me -- mail@hostvpn.com -- and I can try to see if I can diagnose further with you.

**Comment by hostvpn** [comment]
I just merged a pull request with some updates to the Coinbase API, can you give it another try with the latest commit?
